version: '3'
services:
  mongo:
    image: mongo:4.2.6-bionic
    restart: unless-stopped
    volumes:
      - /home/ubuntu/volumes/mongo:/data/db
    ports:
      - 27017:27017

  microservice:
    build: ./microservice
    depends_on:
      - mongo
    ports:
      - '12000:12000'
